export enum League {
  NHL = 'NHL',
  NFL = 'NFL',
  NBA = 'NBA',
  MLB = 'MLB',
  MLS = 'MLS',
  PWHL = 'PWHL',
  WNBA = 'WNBA',
  NCAAF = 'NCAAF',
  NCAAB = 'NCAAB',
  NCCABB = 'NCCABB',
  WNCAAB = 'WNCAAB',
  NCAAVB = 'NCAAVB',
  NCAAMH = 'NCAAMH',
  NCAAS = 'NCAAS',
  NCAAWH = 'NCAAWH',
  UFL = 'UFL',
  NWSL = 'NWSL',
  'OLYMPICS-MEN' = 'OLYMPICS-MEN',
  'OLYMPICS-WOMEN' = 'OLYMPICS-WOMEN',
}

export enum CollegeLeague {
  NCAAF = 'NCAAF',
  NCAAB = 'NCAAB',
  NCCABB = 'NCCABB',
  WNCAAB = 'WNCAAB',
  NCAAVB = 'NCAAVB',
  NCAAMH = 'NCAAMH',
  NCAAS = 'NCAAS',
  NCAAWH = 'NCAAWH',
}
