export enum League {
  NHL = 'NHL',
  NFL = 'NFL',
  NBA = 'NBA',
  MLB = 'MLB',
  MLS = 'MLS',
  PWHL = 'PWHL',
  WNBA = 'WNBA',
  NCAAF = 'NCAAF',
  NCAAB = 'NCAAB',
  NCCABB = 'NCCABB',
  WNCAAB = 'WNCAAB',
  'OLYMPICS_HOCKEY_MEN' = 'OLYMPICS-MEN',
  'OLYMPICS_HOCKEY_WOMEN' = 'OLYMPICS-WOMEN',
  // 'OLYMPICS_BASKETBALL_MEN' = 'OLYMPICS-B-MEN',
  // 'OLYMPICS_BASKETBALL_WOMEN' = 'OLYMPICS-B-WOMEN',
}

export enum CollegeLeague {
  NCAAF = 'NCAAF',
  NCAAB = 'NCAAB',
  NCCABB = 'NCCABB',
  WNCAAB = 'WNCAAB',
}
