export const TeamsEnum: Record<string, string> = {
  'NCAAB-AKR': 'Akron Zips',
  'NCAAB-APP': 'App State Mountaineers',
  'NCAAB-ARST': 'Arkansas State Red Wolves',
  'NCAAB-BEL': 'Belmont Bruins',
  'NCAAB-BGSU': 'Bowling Green Falcons',
  'NCAAB-CLE': 'Cleveland State Vikings',
  'NCAAB-CLT': 'Charlotte 49ers',
  'NCAAB-COFC': 'Charleston Cougars',
  'NCAAB-CSUN': 'Cal State Northridge Matadors',
  'NCAAB-DRKE': 'Drake Bulldogs',
  'NCAAB-ECU': 'East Carolina Pirates',
  'NCAAB-ETSU': 'East Tennessee State Buccaneers',
  'NCAAB-FAU': 'Florida Atlantic Owls',
  'NCAAB-FRES': 'Fresno State Bulldogs',
  'NCAAB-FUR': 'Furman Paladins',
  'NCAAB-GASO': 'Georgia Southern Eagles',
  'NCAAB-GAST': 'Georgia State Panthers',
  'NCAAB-HOF': 'Hofstra Pride',
  'NCAAB-IONA': 'Iona Gaels',
  'NCAAB-JMU': 'James Madison Dukes',
  'NCAAB-LBSU': 'Long Beach State Beach',
  'NCAAB-LIB': 'Liberty Flames',
  'NCAAB-LT': 'Louisiana Tech Bulldogs',
  'NCAAB-MEM': 'Memphis Tigers',
  'NCAAB-MER': 'Mercer Bears',
  'NCAAB-MONT': 'Montana Grizzlies',
  'NCAAB-MOST': 'Missouri State Bears',
  'NCAAB-MRSH': 'Marshall Thundering Herd',
  'NCAAB-MTST': 'Montana State Bobcats',
  'NCAAB-MTSU': 'Middle Tennessee Blue Raiders',
  'NCAAB-NCAT': 'North Carolina A&T Aggies',
  'NCAAB-NMSU': 'New Mexico State Aggies',
  'NCAAB-NOLA': 'LSU New Orleans Privateers',
  'NCAAB-OAK': 'Oakland Golden Grizzlies',
  'NCAAB-ODU': 'Old Dominion Monarchs',
  'NCAAB-OHIO': 'Ohio Bobcats',
  'NCAAB-ORST': 'Oregon State Beavers',
  'NCAAB-PFW': 'Purdue Fort Wayne Mastodons',
  'NCAAB-PRIN': 'Princeton Tigers',
  'NCAAB-RAD': 'Radford Highlanders',
  'NCAAB-RGV': 'UT Rio Grande Valley Vaqueros',
  'NCAAB-RICE': 'Rice Owls',
  'NCAAB-RICH': 'Richmond Spiders',
  'NCAAB-SAM': 'Samford Bulldogs',
  'NCAAB-SFA': 'Stephen F. Austin Lumberjacks',
  'NCAAB-SHU': 'Sacred Heart Pioneers',
  'NCAAB-SUU': 'Southern Utah Thunderbirds',
  'NCAAB-TEM': 'Temple Owls',
  'NCAAB-TLSA': 'Tulsa Golden Hurricane',
  'NCAAB-TNST': 'Tennessee State Tigers',
  'NCAAB-TOW': 'Towson Tigers',
  'NCAAB-TROY': 'Troy Trojans',
  'NCAAB-TULN': 'Tulane Green Wave',
  'NCAAB-UCD': 'UC Davis Aggies',
  'NCAAB-UCI': 'UC Irvine Anteaters',
  'NCAAB-UCSB': 'UC Santa Barbara Gauchos',
  'NCAAB-UNCG': 'UNC Greensboro Spartans',
  'NCAAB-UNCO': 'Northern Colorado Bears',
  'NCAAB-UNCW': 'UNC Wilmington Seahawks',
  'NCAAB-UND': 'North Dakota Fighting Hawks',
  'NCAAB-UNH': 'New Hampshire Wildcats',
  'NCAAB-UNI': 'Northern Iowa Panthers',
  'NCAAB-UNLV': 'UNLV Rebels',
  'NCAAB-UNM': 'New Mexico Lobos',
  'NCAAB-UNT': 'North Texas Mean Green',
  'NCAAB-USM': 'Southern Miss Golden Eagles',
  'NCAAB-UTA': 'UT Arlington Mavericks',
  'NCAAB-UTEP': 'UTEP Miners',
  'NCAAB-UTSA': 'UTSA Roadrunners',
  'NCAAB-UVM': 'Vermont Catamounts',
  'NCAAB-VAL': 'Valparaiso Beacons',
  'NCAAB-VCU': 'VCU Rams',
  'NCAAB-W&M': 'William & Mary Tribe',
  'NCAAB-WCU': 'Western Carolina Catamounts',
  'NCAAB-WEB': 'Weber State Wildcats',
  'NCAAB-WIN': 'Winthrop Eagles',
  'NCAAB-WOF': 'Wofford Terriers',
  'NCAAB-WRST': 'Wright State Raiders',
  'NCAAB-WYO': 'Wyoming Cowboys',
  'NCAAB-YSU': 'Youngstown State Penguins',
  'NCAAF-BRWN': 'Brown Bears',
  'NCAAF-COLU': 'Columbia Lions',
  'NCAAF-COR': 'Cornell Big Red',
  'NCAAF-DART': 'Dartmouth Big Green',
  'NCAAF-DRKE': 'Drake Bulldogs',
  'NCAAF-HARV': 'Harvard Crimson',
  'NCAAF-JKST': 'Jackson State Tigers',
  'NCAAF-MORE': 'Morehead State Eagles',
  'NCAAF-MRST': 'Marist Red Foxes',
  'NCAAF-NCCU': 'North Carolina Central Eagles',
  'NCAAF-PENN': 'Pennsylvania Quakers',
  'NCAAF-PRES': 'Presbyterian Blue Hose',
  'NCAAF-PRIN': 'Princeton Tigers',
  'NCAAF-SFA': 'Stephen F. Austin Lumberjacks',
  'NCAAF-STMN': 'St. Thomas Tommies',
  'NCAAF-TNTC': 'Tennessee Tech Golden Eagles',
  'NCAAF-USD': 'San Diego Toreros',
  'NCAAF-VAL': 'Valparaiso Beacons',
  'NCAAF-W&M': 'William & Mary Tribe',
  'NCAAMH-OAK': 'Oakland Golden Grizzlies',
  'NCAAWH-NMU': 'Northern Michigan Wildcats',
  'PWHL-DET': 'Pwhl Detroit',
  'PWHL-HAM': 'Pwhl Hamilton',
  'PWHL-SJ': 'Pwhl San Jose',
  'PWHL-VEG': 'Pwhl Las Vegas',
  'WNCAAB-BEL': 'Belmont Bruins',
  'WNCAAB-BUT': 'Butler Bulldogs',
  'WNCAAB-DRAKE': 'Drake Bulldogs',
  'WNCAAB-EVAN': 'Evansville Purple Aces',
  'WNCAAB-ILST': 'Illinois State Redbirds',
  'WNCAAB-ISU-BLUE': 'Indiana State Sycamores',
  'WNCAAB-MARQ': 'Marquette Golden Eagles',
  'WNCAAB-NCST': 'NC State Wolfpack',
  'WNCAAB-RU': 'Rutgers Scarlet Knights',
  'WNCAAB-TAMU': 'Texas A&M Aggies',
  'WNCAAB-UNI': 'Northern Iowa Panthers',
  'WNCAAB-VALPO': 'Valparaiso Beacons',
  'WNCAAB-VANDY': 'Vanderbilt Commodores',
};
