// This file is generated by TeamService.generateLeaguesTeamsAndColorsFiles()
// It mirrors the frontend constants/UniversityLogos.tsx mapping using the team
// abbreviation as the key.  When ESPN doesn't provide a logo, the backend can
// fall back to this map to keep games and teams nicely populated.

export const UniversityLogos: Record<string, string> = {
  // regenerated automatically; do not edit manually
};
